update

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -50,18 +50,18 @@ else
     exit 1
 fi
 
-LDFLAGS="-L$build/lib" CFLAGS="-I$buildinclude" PKG_CONFIG_PATH="$build"
-./configure --datadir=$build --disable-sse2
-make -j4
-make install DESTDIR="$build"
+# LDFLAGS="-L$build/lib" CFLAGS="-I$buildinclude" PKG_CONFIG_PATH="$build"
+# ./configure --datadir=$build --disable-sse2
+# make -j4
+# make install DESTDIR="$build"
 
 
-# Confirm installation
-if [ -d "$build/libpostal" ]; then
-    echo "libpostal installed successfully."
-else
-    echo "libpostal installation failed."
-    exit 1
-fi
+# # Confirm installation
+# if [ -d "$build/libpostal" ]; then
+#     echo "libpostal installed successfully."
+# else
+#     echo "libpostal installation failed."
+#     exit 1
+# fi
 
-echo "-----> Installation completed successfully"
+# echo "-----> Installation completed successfully"
