update

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -44,8 +44,12 @@ cd libpostal/
 make
 make install DESTDIR="$build/libpostal"
 
-# Move installed directories to the build folder
-# mv /app/snappy "$build"
-mv /app/libpostal "$build"
+# Confirm installation
+if [ -d "$build/libpostal" ]; then
+    echo "libpostal installed successfully."
+else
+    echo "libpostal installation failed."
+    exit 1
+fi
 
 echo "-----> Installation completed successfully"
