update

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -39,19 +39,29 @@ echo "-----> Downloading libpostal"
 git clone https://github.com/openvenues/libpostal --depth 1
 cd libpostal/
 ./bootstrap.sh
-echo "----> suh dude $buildinclude"
-# LDFLAGS="-L$build/lib" CFLAGS="-I$buildinclude" PKG_CONFIG_PATH="$build"
-# ./configure --datadir=$build --disable-sse2
-# make -j4
-# make install DESTDIR="$build"
+
+# Search for libpostal.pc in the build directory
+libpostal_pc=$(find "$build" -name "libpostal.pc" 2>/dev/null)
+
+if [ -n "$libpostal_pc" ]; then
+    echo "libpostal.pc found at: $libpostal_pc"
+else
+    echo "libpostal.pc not found. Installation may have failed."
+    exit 1
+fi
+
+LDFLAGS="-L$build/lib" CFLAGS="-I$buildinclude" PKG_CONFIG_PATH="$build"
+./configure --datadir=$build --disable-sse2
+make -j4
+make install DESTDIR="$build"
 
 
-# # Confirm installation
-# if [ -d "$build/libpostal" ]; then
-#     echo "libpostal installed successfully."
-# else
-#     echo "libpostal installation failed."
-#     exit 1
-# fi
+# Confirm installation
+if [ -d "$build/libpostal" ]; then
+    echo "libpostal installed successfully."
+else
+    echo "libpostal installation failed."
+    exit 1
+fi
 
-# echo "-----> Installation completed successfully"
+echo "-----> Installation completed successfully"
